version: 2 #Version dbt

sources:
  - name: raw #Alias su dbt
    schema: gz_raw_data #Nome dataset su Bigquery
    tables:
      - name: product #Alias
        identifier: raw_gz_product #Nome tabella BQ
      - name: sales
        identifier: raw_gz_sales
      - name: ship
        identifier: raw_gz_ship